# Generated by Django 2.2.12 on 2020-04-27 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('species', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('race', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image_url', models.TextField(blank=True, max_length=800, null=True)),
                ('google_id', models.CharField(blank=True, max_length=80, null=True)),
                ('type_of_profile', models.CharField(choices=[('ADO', 'Adopter'), ('REF', 'Refugio'), ('ADM', 'Admin')], default='ADO', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rest_api.Animal')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='rest_api.Profile'),
        ),
    ]
