# Generated by Django 2.1.7 on 2020-04-21 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_create_superuser'),
    ]

    operations = [
    ]
