# Generated by Django 2.2.12 on 2020-06-04 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_create_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('short_description', models.CharField(max_length=255, verbose_name='Descripcion corta')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('status_request', models.CharField(default='Disponible', max_length=30, verbose_name='Estado de colaboración')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('colaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='rest_api.Profile', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Colaboración',
                'verbose_name_plural': 'Colaboraciones',
            },
        ),
    ]
