# Generated by Django 2.2.12 on 2020-06-04 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_colaboration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboration',
            name='colaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colaborations_of_user', to='rest_api.Profile', verbose_name='Colaborador'),
        ),
    ]
