# Generated by Django 2.1.7 on 2020-04-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20200421_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='race',
            field=models.TextField(blank=True, null=True),
        ),
    ]
