# Generated by Django 2.2.12 on 2020-07-05 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_create_example_colaborations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha modificación'),
        ),
        migrations.AlterField(
            model_name='colaboration',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='colaboration',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha fin'),
        ),
        migrations.AlterField(
            model_name='colaboration',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha modificación'),
        ),
        migrations.AlterField(
            model_name='colaboration',
            name='required_colaborators',
            field=models.IntegerField(default=1, verbose_name='Colaboradores requeridos'),
        ),
        migrations.AlterField(
            model_name='colaboration',
            name='satisfied',
            field=models.BooleanField(default=False, verbose_name='Satisfecha'),
        ),
        migrations.AlterField(
            model_name='colaborationcolaborators',
            name='colaboration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colaboration_colab', to='rest_api.Colaboration', verbose_name='Colaboración'),
        ),
        migrations.AlterField(
            model_name='colaborationcolaborators',
            name='colaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colaboration_users', to='rest_api.Profile', verbose_name='Colaboradores'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha modificación'),
        ),
        migrations.AlterField(
            model_name='refugioevent',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='refugioevent',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha modificación'),
        ),
    ]
