# Generated by Django 2.2.12 on 2020-07-05 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_auto_20200705_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='potencial_adopter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adopter_requests', to='rest_api.Profile', verbose_name='Usuario adoptante'),
        ),
    ]
