# Generated by Django 2.2.12 on 2020-06-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboration',
            name='colaborator',
        ),
        migrations.AddField(
            model_name='colaboration',
            name='colaborators',
            field=models.ManyToManyField(to='rest_api.Profile'),
        ),
    ]
