# Generated by Django 2.2.12 on 2020-06-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20200610_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboration',
            name='required_colaborators',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='colaboration',
            name='satisfied',
            field=models.BooleanField(default=False),
        ),
    ]
