# Generated by Django 2.2.12 on 2020-06-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_auto_20200610_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboration',
            name='colaborators',
            field=models.ManyToManyField(blank=True, to='rest_api.Profile'),
        ),
    ]
