# Generated by Django 2.2.12 on 2020-07-07 01:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_auto_20200705_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='long_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
    ]
