# Generated by Django 2.2.12 on 2020-07-11 05:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0011_auto_20200711_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
