# Generated by Django 2.2.12 on 2020-07-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0012_auto_20200711_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status_request',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Rechazado', 'Rechazado'), ('Aceptado', 'Aceptado')], default='Disponible', max_length=30, verbose_name='Estado de denuncia'),
        ),
    ]
